main/urls.py
from django.contrib import admin
from django.urls import path
from main import views


app_name = 'main' # 템플릿에서 url로 사용하기 위함
urlpatterns = [
    # path('', views.home),
    # path('product/', views.product),
    # path('main/insert/', views.insert),
    path('', views.index, name = 'index'),
    # ex: /main/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /main/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('home/', views.home, name = 'home'),
    # path('home/insert/<int:code_id>', views.insert, name = 'insert'),
    # path('home/ins/', views.ins, name = 'ins'),
    path('home/add/', views.add, name='add'),
    path('home/<int:code_id>/', views.post_detail, name='post_detail'), # code_id란 변수로 view에 넘겨주기
    path('home/<int:code_id>/edit/', views.post_edit, name='post_edit'), 
    path('home/<int:code_id>/delete', views.post_delete, name='post_delete'),

    path('upload/', views.upload_image, name='upload_image'),
    path('upload/<int:img_id>/', views.img_detail, name='img_detail'),
    path('home/img_add', views.img_add, name="img_add"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main' # 템플릿에서 url로 사용하기 위함
urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Bar_code(models.Model):
    code = models.CharField(max_length=20)
    name = models.CharField(max_length=30)
    charge = models.IntegerField()

    def __str__(self):
        return self.name

class Review(models.Model):
    code_name = models.ForeignKey(Bar_code, on_delete=models.CASCADE) # 외래키이므로 위에 question을 참조하고 삭제되면 같이 삭제
    review_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.review_text

class Img(models.Model):
    title = models.CharField(max_length=20)
    image = models.ImageField(upload_to='images/%Y/%M/%D')

    def __str__(self):
        return self.title

class Imgadd(models.Model):
    code_img = models.ImageField(upload_to='images/%Y/%M/%D')
    name = models.CharField(max_length=30)
    charge = models.IntegerField()

    def __str__(self):
        return self.name


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE) # 외래키이므로 위에 question을 참조하고 삭제되면 같이 삭제
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

main/forms.py
from django import forms

from .models import Bar_code, Img, Imgadd

class PostForm(forms.ModelForm):

    class Meta:
        model = Bar_code
        fields = ('code', 'name', 'charge',)

class UploadForm(forms.ModelForm):
    
    class Meta:
        model = Img
        fields = ( 'title','image', )

class Post2Form(forms.ModelForm):

    class Meta:
        model = Imgadd
        fields = ('code_img', 'name', 'charge',)

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# from django.http import Http404
# from django.template import loader
from .forms import PostForm, UploadForm, Post2Form
from django.utils import timezone

from main.models import Question, Bar_code, Img, Imgadd
from .bar_read import bar_read
from django.conf import settings

# Create your views here.

# def home(request):
#     return render(request, 'main/home.html')
# def product(request):
#     return render(request, 'main/product.html')
# def insert(request):
#     return render(request, 'mian/insert.html')

def home(request):
    code_list = Bar_code.objects.all()
    # if code_id is not None:
    #     code = get_object_or_404(Bar_code, pk=code_id)
    #     return render(request, 'main/insert.html', {'code':code})
    return render(request, 'main/home.html', {'code_list':code_list})

# def ins(request, code_id):
#     # if code_id is not None:
#     code = get_object_or_404(Bar_code, pk=code_id)
#     return render(request, 'main/home/ins.html', {'code':code})
#     # return HttpResponseRedirect('/main/home/')
#     # return render(request, 'main/home/insert.html')

def ins(request):
    return render(request, 'main/ins.html')

# def add(request, code_id):
#     code = get_object_or_404(Bar_code, pk=code_id)
#     try:
#         selected_code = code.objects.get(pk=request.POST['add'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'main/detail.html', {
#             'code': code,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_code.votes += 1
#         selected_code.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('main:results', args=(code.id,)))

# def add(request):
#     if request.method == 'POST':
#         Bar_code(
#             code = request.POST.get('code'),
#             name = request.POST.get('name'),
#             charge = request.POST.get('charge'),
#         ).save()
#     return HttpResponseRedirect('/main/home')

# def add(request, code_id):
#     code = get_object_or_404(Bar_code, pk=code_id)
#     try:
#         add_code = code.choice_set.get(pk=request.POST['code'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'main/home.html', {
#             'code': code,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         add_code.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('main:home', args=(code.id,)))


def add(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('/main/home')
    else:
        form = PostForm()
    return render(request, 'main/add.html', {'form': form})

def post_detail(request, code_id): # code_id 가져오기
    post = get_object_or_404(Bar_code, pk=code_id)
    return render(request, 'main/post_detail.html', {'post': post})

def post_edit(request, code_id):
    post = get_object_or_404(Bar_code, pk=code_id) # post.id로 입력해야함 post_detail.html에서
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('/main/home')
    else:
        form = PostForm(instance=post)
    return render(request, 'main/add.html', {'form': form})

def post_delete(request, code_id):
    post = Bar_code.objects.get(id=code_id)
    post.delete()
    return redirect('/main/home')

def upload_image(request):
    img_list = Img.objects.all()
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            imageURL = settings.MEDIA_URL + form.instance.image.name
            bar_read(settings.MEDIA_ROOT_URL + imageURL)
            return redirect('/main/upload')
    else:
        form = UploadForm()
    return render(request, 'main/upload.html', {'form':form, 'img_list':img_list})

def img_detail(request, img_id):
    post = get_object_or_404(Img, pk=img_id)
    result = bar_read(post.image.path)
    return render(request, 'main/img_detail.html', {'post':post, 'result':result})

def img_add(request):
    img_list = Img.objects.all()
    if request.method == 'POST':
        form = Post2Form(request.POST, request.FILES)
        if form.is_valid():
            imageURL = settings.MEDIA_URL + form.instance.image.name
            post.code = bar_read(settings.MEDIA_ROOT_URL + imageURL)
            post.save()
            form.save()
            return redirect('/main/home')
    else:
        form = Post2Form()
    return render(request, 'main/img_add.html', {'form':form, 'img_list':img_list})






def index(request):
    # return HttpResponse("Hello, world.")
    latest_question_list = Question.objects.order_by('-pub_date')[:5] # Question 데이터 중에서 출판일자를 정렬하여 5개까지만 데이터 가져오기
    # output = ', '.join([q.question_text for q in latest_question_list]) # 그리고 이 다섯개 데이터를 ,로 연결하겠다
    context = {'latest_question_list' : latest_question_list}
    return render(request, 'main/index.html', context) 

def detail(request, question_id):
    # return HttpResponse("you're looking at question %s." % question_id)
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    # return render(request, 'main/detail.html', {'question':question})
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'main/detail.html', {'question':question})

def results(request, question_id):
    # return HttpResponse(response % question_id)
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'main/results.html', {'question': question})

# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'main/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('main:results', args=(question.id,)))

main/templates/main/add.html
{% block content %}
    <h1>상품입력</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
    
        <button type="submit" class="save btn btn-default">저장</button>
    </form>
{% endblock %}

main/templates/main/detail.html
<!-- {{ question }} -->

<!-- <h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul> -->

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'main:vote' question.id %}" method="post"> <!--submit을 눌렀을 때 해당 url로 넘어감-->
{% csrf_token %} <!--해킹 방지-->
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"> <!--submit을 누르면 value값이 넘어감-->
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

main/templates/main/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
</head>
<body>
    <h1>상품목록</h1>
    <!--<tr>
        <th>코드</th><th>상품</th><th>단가</th>
        <th>변경</th>
    </tr> -->
    {% if code_list %}
    <ul>
        {% for codes in code_list %}
            <h1><a href="{% url 'main:post_detail' codes.id %}">{{ codes.name }}</a></h1>
            <p>바코드 : {{ codes.code }}</p>
            <p>가격 : {{ codes.charge }}</p>
            <br>
        {% endfor %}
    </ul>
    {% else %}
        <p>자료가 없습니다.</p>
    {% endif %}
    <a href="{% url 'main:add' %}">바코드로 상품추가</a><br>
    <a href="{% url 'main:img_add' %}">이미지로 상품추가</a>
</body>
</html>

main/templates/main/img_add.html
{% block content %}
    <h1>상품입력</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="save btn btn-default">저장</button>
    </form>
{% endblock %}

main/templates/main/img_detail.html
{% block content %}
    {% if post.id %}

        <p>제목 : {{ post.title }}</p>

    {% endif %}
    <br>
    <img src="{{ post.image.url }}"><br>
    <p>{{ result }}</p>
{% endblock %}

main/templates/main/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href={% url 'main:detail' question.id %}>{{ question.question_text }}</a></li>
            {% endfor %}
    </ul>
{% else %}
    <p>No main are available.</p>
{% endif %}

main/templates/main/ins.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<script type="text/javascript">
function chkData() {
    //alert("aa");
    if(frm.code.value == "" ||
        frm.name.value == "" ||
        frm.volume.value == "" ||
        frm.charge.value == ""){
        alert("입력자료를 모두 채우시오");
        return;
    }
    frm.submit();
}

</script>
</head>
<body>
<!-- <h2>자료 입력</h2>
<form name="frm" action="/main/product" method="post">{% csrf_token%}
<table border="1">
    <tr><td>코드 : </td><td><input type="text" name="code"></td></tr>
    <tr><td>품명 : </td><td><input type="text" name="sang"></td></tr>
    <tr><td>수량 : </td><td><input type="text" name="su"></td></tr>
    <tr><td>단가 : </td><td><input type="text" name="dan"></td></tr>
    <tr>
     <td colspan="2" style="text-align:center;">
     <input type="button" value="저장" onclick="chkData()">
     </td>
    </tr>
</table>
</form> -->
<h1>{{ code.code_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form name = "frm" action="{% url 'main:add' %}" method="post"> <!--submit을 눌렀을 때 해당 url로 넘어감-->
{% csrf_token %} <!--해킹 방지-->

    <!-- <input type="radiot" name="add" id="add{{ forloop.counter }}" value="{{ add.id }}"> submit을 누르면 value값이 넘어감 -->
    <!-- <label for="add{{ forloop.counter }}">{{ choice.choice_text }}</label><br> -->
    <input type="text" name="add_code" value="{{ add.code }}">
    <input type="text" name="add_name">
    <input type="text" name="add_charge">

<input type="submit" value="저장" onclick="chkData()">
</form>
</body>
</html>

main/templates/main/post_detail.html
{% block content %}
    {% if post.id %}

        <p>바코드 : {{ post.code }}</p>

    {% endif %}
    <br>
    <h1>상품명 : {{ post.name }}</h1>
    <p>가격 : {{ post.charge }}</p>
    <a href="{% url 'main:post_edit' post.id %}">상품수정</a>
    <div class="delete">
        <p><a href="{% url 'main:post_delete' post.id %}">삭제</a></p>  
    </div>
{% endblock %}

main/templates/main/product.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<h2>* 상품 목록 *</h2>
<a href="/main/insert">상품 추가</a>
<table border="1">
<tr>
    <th>id</th><th>코드</th><th>상품</th><th>수량</th><th>단가</th>
    <th>변경</th>
</tr>
{% if sangpums %}
{% for s in sangpums %}
<tr>
    <td>{{s.id}}</td>
    <td>{{s.code}}</td>
    <td>{{s.name}}</td>
    <td>{{s.volume}}</td>
    <td>{{s.charge}}</td>
    <td>
        <a href="/sangpum/update?id={{s.id}}">수정</a> /
        <a href="/sangpum/delete?id={{s.id}}">삭제</a>
    </td>
</tr>
{% endfor %}
{% else %}
    <tr><td colspan="5"> 자료가 없음 </td></tr>
{% endif %}
</table>
</body>
</html>

main/templates/main/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'main:detail' question.id %}">Vote again?</a>

main/templates/main/upload.html
{% block content %}
    <h2>Upload image</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Upload</button>
    </form>
    <br><br>
    <h1>이미지들</h1>
    <ul>
        {% for img in img_list %}
            <p><a href="{% url 'main:img_detail' img.id %}">{{ img.title }}</a></p>
            <p><img src='{{ img.image.url }}'></p>
            <p>{{ result }}</p>
        {% endfor %}
    </ul>
    
{% endblock %}